[build.environment]
    NPM_FLAGS = "--version"
[build]
    command = "npx pnpm install --store=node_modules/.pnpm-store && pnpm build"
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200